import Head from 'next/head'
import { Inter } from '@next/font/google'
import useJunks from '@/hooks/use-junks'
import { Fragment } from 'react';

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"]
})

export default function Home() {
  const { junks, isLoading, error } = useJunks();
  return (
    <>
      <Head>
        <title>The Junk Book</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main 
        style={inter.style} 
        className="bg-brwhite text-brblack flex flex-col"
      >
        
      </main>
    </>
  )
}
